# Generated by Django 4.1.1 on 2022-10-31 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee_salasry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empid', models.CharField(max_length=20, null=True)),
                ('basic_Salary', models.FloatField(null=True)),
                ('OT_houres', models.PositiveIntegerField(null=True)),
                ('OT_Rate', models.FloatField(null=True)),
                ('deduction', models.FloatField(null=True)),
                ('increment', models.FloatField(null=True)),
                ('total_sal', models.FloatField(null=True)),
                ('date', models.DateField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('category', models.CharField(choices=[('Womens', 'Womens'), ('Mens', 'Mens'), ('Kids', 'Kids')], max_length=20, null=True)),
                ('quantity', models.PositiveIntegerField(null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='utilitybill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_id', models.CharField(max_length=20, null=True)),
                ('category', models.CharField(choices=[('Electricity', 'Electricity'), ('Water', 'Water')], max_length=20, null=True)),
                ('date', models.DateField(max_length=100, null=True)),
                ('price', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='fashion_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplierId', models.PositiveIntegerField(null=True)),
                ('ordermngrId', models.PositiveIntegerField(null=True)),
                ('quantity_order', models.PositiveIntegerField(null=True)),
                ('orderDate', models.DateField(max_length=100, null=True)),
                ('status', models.BooleanField(null=True)),
                ('total_price', models.FloatField(null=True)),
                ('ordermngrName', models.CharField(max_length=50, null=True)),
                ('supplieName', models.CharField(max_length=50, null=True)),
                ('item_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.item')),
            ],
        ),
    ]
