# Generated by Django 4.1.1 on 2022-11-02 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0001_initial'),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fashion_order',
            name='item_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockapp.item'),
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
