# Generated by Django 4.1.1 on 2022-11-02 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0001_initial'),
        ('dashboard', '0004_alter_fashion_order_item_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fashion_order',
            name='item_Id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stockapp.item'),
        ),
    ]
