# Generated by Django 4.1.1 on 2022-10-18 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='leave_types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(max_length=45, null=True)),
                ('description', models.CharField(max_length=45, null=True)),
            ],
            options={
                'db_table': 'leave_types',
            },
        ),
        migrations.RemoveField(
            model_name='leave',
            name='type',
        ),
        migrations.AddField(
            model_name='employee_positions',
            name='description',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='leave',
            name='leaveType',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='employee_positions',
            name='name',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='employeesreg',
            name='empid',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='employeesreg',
            name='fname',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='employeesreg',
            name='lname',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='employeesreg',
            name='password',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employeesreg',
            name='position',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='date',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='empid',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='reason',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='status',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
