# Generated by Django 4.1.1 on 2022-11-03 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_code',
            field=models.IntegerField(null=True),
        ),
    ]
