# Generated by Django 4.1.1 on 2022-10-31 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(max_length=10, null=True)),
                ('Item_code', models.CharField(max_length=100)),
                ('Item_name', models.CharField(max_length=100, null=True)),
                ('Size', models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L')], max_length=100, null=True)),
                ('Price', models.CharField(max_length=100)),
                ('total_price', models.FloatField(null=True)),
                ('QTY', models.PositiveIntegerField(null=True)),
            ],
        ),
    ]
