# Generated by Django 4.1.1 on 2022-10-31 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='Price',
            field=models.FloatField(max_length=100),
        ),
    ]
