# Generated by Django 4.1.1 on 2022-10-31 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesapp', '0002_alter_sales_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='Price',
            field=models.FloatField(null=True),
        ),
    ]
