# Generated by Django 4.1.1 on 2022-11-03 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplierId', models.PositiveIntegerField()),
                ('ordermngrId', models.PositiveIntegerField()),
                ('supplierName', models.CharField(max_length=40, null=True)),
                ('ordermngrName', models.CharField(max_length=40, null=True)),
                ('orderDate', models.DateField(auto_now=True)),
                ('item_code', models.CharField(max_length=10)),
                ('brand', models.CharField(max_length=100, null=True)),
                ('colour', models.CharField(max_length=20, null=True)),
                ('size', models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL')], max_length=20, null=True)),
                ('category', models.CharField(choices=[('Womens', 'Womens'), ('Mens', 'Mens'), ('Kids', 'Kids')], max_length=20, null=True)),
                ('quantity', models.PositiveIntegerField()),
                ('status', models.BooleanField(default=False)),
                ('total_price', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SupplierCancelDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplierId', models.PositiveIntegerField()),
                ('supplierName', models.CharField(max_length=40)),
                ('assignedOrdermngrName', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=40)),
                ('mobile', models.PositiveIntegerField(max_length=10, null=True)),
                ('item_code', models.CharField(max_length=10, null=True)),
                ('brand', models.CharField(max_length=100, null=True)),
                ('colour', models.CharField(max_length=20, null=True)),
                ('size', models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL')], max_length=20, null=True)),
                ('category', models.CharField(choices=[('Womens', 'Womens'), ('Mens', 'Mens'), ('Kids', 'Kids')], max_length=20, null=True)),
                ('confirmedDate', models.DateField()),
                ('cancelledDate', models.DateField()),
                ('units', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField()),
                ('Othercharges', models.PositiveIntegerField()),
                ('Transportfee', models.PositiveIntegerField()),
                ('total', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pic/SupplierProfilePic/')),
                ('address', models.CharField(max_length=40)),
                ('mobile', models.PositiveIntegerField(max_length=10)),
                ('email', models.EmailField(max_length=100)),
                ('item_code', models.CharField(max_length=100)),
                ('assignedOrdermngrId', models.PositiveIntegerField()),
                ('confirmedDate', models.DateField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ordermngr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pic/OrdermngrProfilePic/')),
                ('address', models.CharField(max_length=40)),
                ('mobile', models.PositiveIntegerField(max_length=10, null=True)),
                ('department', models.CharField(choices=[('Kids', 'Kids'), ('Teens', 'Teens'), ('Gents', 'Gents'), ('Ladies', 'Ladies'), ('Officewear', 'Officewear'), ('Baby', 'Baby')], default='Kids', max_length=50)),
                ('status', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
